'------------------------------------------------------------------------------
' <auto-generated>
'     Этот код создан по шаблону.
'
'     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
'     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Запись
    Public Property Id As Integer
    Public Property фамилия As String
    Public Property имя As String
    Public Property отчество As String
    Public Property пол As String
    Public Property услуга As String
    Public Property дата As Nullable(Of Date)
    Public Property время As Nullable(Of System.TimeSpan)

End Class
