'------------------------------------------------------------------------------
' <auto-generated>
'     Этот код создан по шаблону.
'
'     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
'     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Услуги
    Public Property Id As Integer
    Public Property название As String
    Public Property цена As Nullable(Of Decimal)
    Public Property продолжительность As Nullable(Of System.TimeSpan)

End Class
